/* ECHO RIFT — manual signalling, bounded messages, no camera/microphone permissions. */
(function(){'use strict';
const VERSION=1;
function encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';for(const b of bytes)s+=String.fromCharCode(b);return 'ER1.'+btoa(s);}
function decode(text,kind){const s=String(text||'').replace(/\s/g,'');if(s.length<20||s.length>40000||!s.startsWith('ER1.'))throw Error('Ungültiger Code. Bitte den vollständigen ER1.-Code einfügen.');let o;try{o=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(atob(s.slice(4)),c=>c.charCodeAt(0))));}catch(e){throw Error('Der Code ist beschädigt oder unvollständig. Bitte erneut kopieren.');}if(o.v!==VERSION||o.kind!==kind||typeof o.sid!=='string'||o.sid.length>80||typeof o.sdp!=='string'||o.sdp.length>26000||!o.sdp.startsWith('v=0'))throw Error('Falscher Code-Typ oder andere Spielversion. Einladung und Antwort nicht vertauschen.');return o;}
function name(s){return String(s||'GAST').replace(/[\u0000-\u001f\u007f-\u009f<>]/g,'').trim().slice(0,16)||'GAST';}
class Peer{
 constructor(callbacks={}){this.callbacks=callbacks;this.closed=false;this.opened=false;this.role='';this.sid='';this.pc=null;this.lastSeen=performance.now();this.rtt=0;this.ctrl=null;this.fast=null;this.heartbeat=null;this.timeout=null;this.cancelGather=null;}
 init(config={}){if(!window.RTCPeerConnection)throw Error('Dieser Browser unterstützt keine Peer-to-Peer-Datenverbindungen. Öffne das Spiel in einem aktuellen Browser.');const iceServers=[];if(config.internet)iceServers.push({urls:'stun:stun.l.google.com:19302'});if(config.turnUrl){if(!/^turns?:[^\s]{3,250}$/.test(config.turnUrl))throw Error('TURN-Adresse muss mit turn: oder turns: beginnen.');iceServers.push({urls:config.turnUrl,username:String(config.turnUser||'').slice(0,256),credential:String(config.turnPass||'').slice(0,1024)});}this.pc=new RTCPeerConnection({iceServers});this.pc.onconnectionstatechange=()=>{if(this.closed)return;const s=this.pc.connectionState;this.callbacks.onState?.(s);};this.ctrl=this.pc.createDataChannel('echo-control',{negotiated:true,id:0,ordered:true});this.fast=this.pc.createDataChannel('echo-realtime',{negotiated:true,id:1,ordered:false,maxRetransmits:0});for(const channel of[this.ctrl,this.fast]){channel.onopen=()=>this.maybeOpen();channel.onmessage=e=>this.receive(e.data);channel.onerror=()=>this.callbacks.onState?.('channel-error');channel.onclose=()=>{if(!this.closed)this.callbacks.onState?.('closed');};}this.callbacks.onState?.('gathering');}
 maybeOpen(){if(this.closed||this.opened||this.ctrl.readyState!=='open'||this.fast.readyState!=='open')return;this.opened=true;clearTimeout(this.timeout);this.lastSeen=performance.now();this.heartbeat=setInterval(()=>{if(this.closed)return;this.send({type:'ping',at:performance.now()});if(performance.now()-this.lastSeen>5500)this.callbacks.onState?.('stalled');},1000);this.callbacks.onState?.('connected');this.callbacks.onOpen?.();}
 receive(raw){if(this.closed||typeof raw!=='string'||raw.length>62000)return;let msg;try{msg=JSON.parse(raw);}catch(e){return;}if(!msg||typeof msg!=='object'||typeof msg.type!=='string')return;this.lastSeen=performance.now();if(msg.type==='ping'){if(Number.isFinite(msg.at))this.send({type:'pong',at:msg.at});return;}if(msg.type==='pong'){if(Number.isFinite(msg.at))this.rtt=Math.max(0,Math.min(9999,Math.round(performance.now()-msg.at)));return;}this.callbacks.onMessage?.(msg);}
 async gather(){const pc=this.pc;await new Promise((resolve,reject)=>{let timer;const finish=(err)=>{clearTimeout(timer);pc.removeEventListener('icegatheringstatechange',changed);this.cancelGather=null;err?reject(err):resolve();};const changed=()=>{if(pc.iceGatheringState==='complete')finish();};this.cancelGather=()=>finish(Error('Verbindungsaufbau abgebrochen.'));timer=setTimeout(()=>finish(),11000);pc.addEventListener('icegatheringstatechange',changed);changed();});if(this.closed)throw Error('Verbindungsaufbau abgebrochen.');const sdp=pc.localDescription?.sdp;if(!sdp||!sdp.includes('a=candidate:'))throw Error('Keine Netzwerk-Kandidaten verfügbar. Browser-/Firewall-Einstellungen prüfen oder über HTTPS öffnen.');return sdp;}
 waitLimit(){clearTimeout(this.timeout);this.timeout=setTimeout(()=>{if(!this.opened&&!this.closed)this.callbacks.onState?.('timeout');},35000);}
 async offer(config,meta={}){this.role='host';this.sid=typeof crypto?.randomUUID==='function'?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);this.init(config);await this.pc.setLocalDescription(await this.pc.createOffer());const sdp=await this.gather();return encode({v:VERSION,kind:'offer',sid:this.sid,sdp,name:name(meta.name)});}
 async answer(code,config,meta={}){const o=decode(code,'offer');this.role='guest';this.sid=o.sid;this.remoteName=name(o.name);this.init(config);await this.pc.setRemoteDescription({type:'offer',sdp:o.sdp});await this.pc.setLocalDescription(await this.pc.createAnswer());const sdp=await this.gather();this.waitLimit();return encode({v:VERSION,kind:'answer',sid:this.sid,sdp,name:name(meta.name)});}
 async accept(code){if(!this.pc||this.role!=='host'||this.pc.signalingState!=='have-local-offer')throw Error('Zuerst eine neue Einladung erstellen.');const o=decode(code,'answer');if(o.sid!==this.sid)throw Error('Diese Antwort gehört zu einer anderen Einladung. Bitte eine frische Antwort anfordern.');this.remoteName=name(o.name);await this.pc.setRemoteDescription({type:'answer',sdp:o.sdp});this.waitLimit();}
 send(obj,fast=false){const ch=fast?this.fast:this.ctrl;if(this.closed||!ch||ch.readyState!=='open'||ch.bufferedAmount>(fast?45000:150000))return false;try{const s=JSON.stringify(obj,(_,v)=>typeof v==='number'?Math.round(v*1000)/1000:v);if(s.length>60000)return false;ch.send(s);return true;}catch(e){return false;}}
 close(){if(this.closed)return;this.closed=true;this.cancelGather?.();clearTimeout(this.timeout);clearInterval(this.heartbeat);for(const ch of[this.ctrl,this.fast])try{ch?.close();}catch(e){}try{this.pc?.close();}catch(e){}this.callbacks={};}
}
window.EchoPeer=Peer;window.EchoNet={encode,decode,name,VERSION};
})();
