const test=require('node:test'),assert=require('node:assert/strict');
require('../public/engine.js');
const {Game,MAPS,STEP,circleRect}=EchoEngine;
function fresh(map=0){const g=new Game({map,target:3,seed:57});g.countdown=0;g.players.forEach(p=>p.inv=0);return g;}
function frames(g,n,inputs=[]){for(let i=0;i<n;i++)g.step(typeof inputs==='function'?inputs(g):inputs);}
test('all three arenas have safe spawns, paired portals and safe drop points',()=>{for(let map=0;map<3;map++){const g=fresh(map);assert.equal(g.map.portals.length,2);for(const p of [...g.players,...g.map.drops])assert(g.free(p.x,p.y,17));}});
test('countdown freezes simulation and movement',()=>{const g=new Game({seed:2}),x=g.players[0].x;frames(g,120,[{x:1}]);assert.equal(g.t,0);assert.equal(g.players[0].x,x);assert(g.countdown>0);});
test('normalized diagonal movement has no speed advantage',()=>{const a=fresh(),b=fresh();a.players[0].x=b.players[0].x=600;a.players[0].y=b.players[0].y=380;a.step([{x:1,y:0}]);b.step([{x:1,y:1}]);assert(Math.abs(Math.hypot(a.players[0].x-600,a.players[0].y-380)-Math.hypot(b.players[0].x-600,b.players[0].y-380))<1e-6);});
test('wall collision prevents walking and dashing through a wall',()=>{const g=fresh(),p=g.players[0];p.x=240;p.y=220;frames(g,20,[{x:1,dash:true}]);assert(p.x<=260.001);assert(!circleRect(p.x,p.y,17.999,g.map.walls[0]));});
test('dash provides burst movement and obeys cooldown',()=>{const g=fresh(),p=g.players[0];p.x=500;p.y=380;g.step([{x:1,dash:true}]);assert(p.x>510);assert.equal(p.dashCd,1.8);frames(g,14,[{x:1,dash:true}]);assert(p.dashCd<1.8);assert.equal(p.dashTime,0);});
test('echo requires history and replays recorded shots',()=>{const g=fresh(),p=g.players[0];assert(!g.activateEcho(p));frames(g,120,[{a:0,fire:true}]);const original=g.totalShots;assert(g.activateEcho(p));assert.equal(p.echoCd,8);assert(!g.activateEcho(p));frames(g,120);assert(g.totalShots>original);assert.equal(g.echoes.length,0);});
test('bullets reflect twice then expire',()=>{const g=fresh();g.bullets=[{id:1,x:60,y:100,vx:-620,vy:0,owner:0,echo:false,life:6,bounces:2,damage:26,portalCd:0}];g.step([]);assert(g.bullets[0].vx>0);assert.equal(g.bullets[0].bounces,1);frames(g,360);assert.equal(g.bullets.length,0);});
test('four direct hits produce a knockout, score and respawn',()=>{const g=fresh(),p=g.players[1];for(let i=0;i<4;i++){p.inv=0;g.damage(p,26,0);}assert.equal(g.players[0].score,1);assert.equal(p.hp,0);assert(p.respawn>0);frames(g,95);assert.equal(p.hp,100);assert.equal(p.respawn,0);assert(p.inv>0);});
test('spawn shield blocks incoming damage',()=>{const g=fresh(),p=g.players[1];p.inv=1;g.damage(p,99,0);assert.equal(p.hp,100);});
test('dash-parry changes projectile ownership and damage',()=>{const g=fresh(),p=g.players[1];p.x=700;p.y=380;p.a=Math.PI;p.dashTime=.1;p.dashX=0;p.dashY=0;g.bullets=[{id:1,x:674,y:380,vx:620,vy:0,owner:0,echo:false,life:1,bounces:2,damage:26,portalCd:0}];g.step([]);assert.equal(g.bullets[0].owner,1);assert.equal(p.parries,1);assert.equal(p.hp,100);assert.equal(g.bullets[0].damage,32);});
test('paired portals teleport players and enforce exit cooldown',()=>{const g=fresh(),p=g.players[0];Object.assign(p,g.map.portals[0]);g.step([]);assert(p.x>1000);assert.equal(p.portalTrips,1);g.step([]);assert.equal(p.portalTrips,1);});
test('a projectile can travel through a portal',()=>{const g=fresh();g.bullets=[{id:1,x:104,y:380,vx:100,vy:0,owner:0,echo:false,life:2,bounces:2,damage:26,portalCd:0}];g.step([]);assert(g.bullets[0].x>1000);assert(g.bullets[0].portalCd>0);});
test('healing caps at 100; powerups expire',()=>{const g=fresh(),p=g.players[0];p.hp=80;g.pickups=[{id:1,x:p.x,y:p.y,type:0,ttl:10}];g.step([]);assert.equal(p.hp,100);g.pickups=[{id:2,x:p.x,y:p.y,type:1,ttl:10}];g.step([]);assert.equal(p.buff,1);frames(g,425);assert.equal(p.buff,0);});
test('storm wave damages once per cycle and dash protects',()=>{const g=fresh();g.t=15.01;g.players.forEach(p=>{p.x=600;p.y=380;p.inv=0;});g.players[1].dashTime=.15;g.step([]);assert.equal(g.players[0].hp,78);assert.equal(g.players[1].hp,100);g.step([]);assert.equal(g.players[0].hp,78);});
test('target score ends the match; later damage cannot change result',()=>{const g=fresh(),p=g.players[1];g.players[0].score=2;g.damage(p,100,0,true);assert(g.done);assert.equal(g.winner,0);assert.equal(g.players[0].echoKills,1);g.players[0].inv=0;g.damage(g.players[0],100,1);assert.equal(g.players[1].score,0);});
test('three minute lead wins and a tie enters sudden death',()=>{const a=fresh();a.t=180;a.players[1].score=1;a.step([]);assert(a.done);assert.equal(a.winner,1);const b=fresh();b.t=180;b.step([]);assert(b.sudden&&!b.done);b.players[0].inv=0;b.damage(b.players[0],100,1);assert(b.done);assert.equal(b.winner,1);});
test('same seed and bot inputs produce identical simulation',()=>{const a=fresh(1),b=fresh(1);for(let i=0;i<1800;i++){a.step([a.bot(0),a.bot(1)]);b.step([b.bot(0),b.bot(1)]);}assert.deepEqual(a.snapshot(),b.snapshot());});
test('long-running matches keep finite positions, bounded arrays and valid health',()=>{for(let map=0;map<3;map++){const g=new Game({map,seed:13,demo:true,target:10,difficulty:2});for(let i=0;i<12000;i++){if(g.done)break;g.step([g.bot(0),g.bot(1)]);assert(g.bullets.length<=170);g.players.forEach(p=>{assert(Number.isFinite(p.x)&&Number.isFinite(p.y));assert(p.hp>=0&&p.hp<=100);assert(p.history.length<=120);});}assert(g.totalShots>30);}});
